# Generated by Django 2.2.5 on 2019-12-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_evaluatepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatepage',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
