# Generated by Django 2.2.5 on 2019-12-17 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191216_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMoviePlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('predict', models.CharField(max_length=10)),
                ('recommend_movie', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Movie')),
            ],
        ),
    ]
