# Generated by Django 2.2.5 on 2019-12-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_recommendedmovieplus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedmovieplus',
            name='recommend_movie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Movie'),
        ),
    ]
